// styles/catalogoStyles.ts
import { StyleSheet } from 'react-native';

export const catalogoStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    backgroundColor: '#28a745',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 4,
  },
  titulo: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  contador: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
  },
  buscaContainer: {
    margin: 16,
    marginBottom: 8,
    position: 'relative',
  },
  buscaInput: {
    borderWidth: 2,
    borderColor: '#28a745',
    borderRadius: 25,
    padding: 14,
    paddingLeft: 45,
    paddingRight: 45,
    backgroundColor: '#fff',
    fontSize: 15,
    color: '#333',
    elevation: 2,
  },
  buscaIcon: {
    position: 'absolute',
    left: 15,
    top: 14,
  },
  limparBusca: {
    position: 'absolute',
    right: 12,
    top: 12,
    backgroundColor: '#6c757d',
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoriasContainer: {
    marginBottom: 12,
  },
  categoriasLista: {
    paddingHorizontal: 16,
    gap: 8,
  },
  categoriaItem: {
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#dee2e6',
    minWidth: 70,
    backgroundColor: '#fff',
    elevation: 1,
  },
  categoriaNome: {
    fontSize: 10,
    textAlign: 'center',
    color: '#333',
    fontWeight: '600',
    marginTop: 4,
  },
  categoriaSelecionada: {
    color: '#ffffffff',
    fontWeight: '700',
  },
  listaProdutos: {
    padding: 12,
    paddingBottom: 30,
    gap: 10,
  },
  produtoCard: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dee2e6',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  produtoPromocao: {
    borderColor: '#dc3545',
    borderWidth: 2,
    backgroundColor: 'rgba(220, 53, 69, 0.03)',
  },
  produtoImagemContainer: {
    marginRight: 14,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  promocaoBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#dc3545',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  promocaoTexto: {
    color: '#fff',
    fontSize: 9,
    fontWeight: 'bold',
  },
  produtoInfo: {
    flex: 1,
  },
  produtoNome: {
    fontSize: 15,
    marginBottom: 2,
    color: '#333',
    fontWeight: '600',
  },
  produtoMarca: {
    fontSize: 11,
    color: '#666',
    marginBottom: 3,
    fontWeight: '500',
  },
  produtoDescricao: {
    fontSize: 12,
    color: '#666',
    lineHeight: 14,
    marginBottom: 3,
  },
  produtoUnidade: {
    fontSize: 10,
    color: '#999',
    marginBottom: 6,
    fontStyle: 'italic',
  },
  precoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  produtoPreco: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#28a745',
  },
  precoPromocao: {
    color: '#dc3545',
  },
  promocaoTag: {
    backgroundColor: '#ffc107',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 5,
  },
  promocaoTagTexto: {
    color: '#000',
    fontSize: 9,
    fontWeight: 'bold',
  },
  vazio: {
    alignItems: 'center',
    padding: 40,
    marginTop: 20,
  },
  vazioTexto: {
    textAlign: 'center',
    color: '#6c757d',
    opacity: 0.8,
    fontSize: 15,
    marginBottom: 6,
    fontWeight: '600',
  },
  vazioDescricao: {
    textAlign: 'center',
    color: '#6c757d',
    opacity: 0.6,
    fontSize: 13,
  },
});