import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: colors.card,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    limparTexto: {
        color: colors.error,
        fontWeight: '600',
        fontSize: 14,
    },
    lista: {
        flex: 1,
    },
    listaConteudo: {
        padding: 20,
        paddingBottom: 120,
    },
    itemCarrinho: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        marginBottom: 12,
        backgroundColor: colors.card,
        borderRadius: 16,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: colors.primary,
    },
    itemInfo: {
        flex: 1,
        marginRight: 12,
    },
    itemPreco: {
        fontSize: 14,
        color: colors.textSecondary,
        marginTop: 4,
        fontWeight: '500',
    },
    itemSubtotal: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.success,
        marginTop: 6,
    },
    controles: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    controleQuantidade: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 4,
    },
    botaoQuantidade: {
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        borderRadius: 10,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    botaoQuantidadeTexto: {
        color: colors.card,
        fontWeight: 'bold',
        fontSize: 16,
        lineHeight: 18,
    },
    quantidade: {
        marginHorizontal: 16,
        fontSize: 16,
        fontWeight: '700',
        minWidth: 24,
        textAlign: 'center',
        color: colors.text,
    },
    botaoRemover: {
        padding: 10,
        backgroundColor: colors.surface,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.error,
    },
    botaoRemoverTexto: {
        fontSize: 18,
        color: colors.error,
    },
    carrinhoVazio: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    carrinhoVazioTexto: {
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 8,
        color: colors.textSecondary,
        textAlign: 'center',
    },
    carrinhoVazioDescricao: {
        fontSize: 16,
        color: colors.textMuted,
        marginBottom: 32,
        textAlign: 'center',
        lineHeight: 22,
    },
    botaoCatalogo: {
        backgroundColor: colors.primary,
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 12,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    botaoCatalogoTexto: {
        color: colors.card,
        fontWeight: '600',
        fontSize: 16,
    },
    resumo: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 24,
        backgroundColor: colors.card,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
    },
    totalTexto: {
        fontSize: 24,
        color: colors.success,
        textAlign: 'center',
        marginBottom: 8,
        fontWeight: '700',
    },
    itensTexto: {
        textAlign: 'center',
        color: colors.textSecondary,
        marginBottom: 20,
        fontSize: 14,
        fontWeight: '500',
    },
    botaoFinalizar: {
        backgroundColor: colors.success,
        padding: 18,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: colors.success,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    botaoFinalizarTexto: {
        color: colors.card,
        fontWeight: '600',
        fontSize: 16,
    },
});