import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    carrinhoBtn: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#3b82f6',
        borderRadius: 12,
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    buscaInput: {
        margin: 20,
        marginBottom: 16,
        borderWidth: 2,
        borderColor: '#e2e8f0',
        borderRadius: 16,
        padding: 16,
        backgroundColor: '#ffffff',
        fontSize: 16,
        fontWeight: '500',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    sectionTitle: {
        marginHorizontal: 20,
        marginBottom: 16,
        fontSize: 18,
        fontWeight: '700',
        color: '#1e293b',
    },
    categoriasContainer: {
        marginHorizontal: 20,
        marginBottom: 24,
    },
    categoriaItem: {
        alignItems: 'center',
        padding: 16,
        borderRadius: 16,
        marginRight: 12,
        minWidth: 90,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
    },
    categoriaIcone: {
        fontSize: 24,
        marginBottom: 8,
    },
    categoriaNome: {
        fontSize: 12,
        textAlign: 'center',
        fontWeight: '600',
    },
    categoriaSelecionada: {
        fontWeight: '700',
        color: '#ffffff',
    },
    listaProdutos: {
        padding: 20,
        paddingBottom: 40,
    },
    produtoCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        marginBottom: 16,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
        borderLeftWidth: 4,
        borderLeftColor: '#10b981',
    },
    produtoInfo: {
        flex: 1,
        marginRight: 16,
    },
    produtoNome: {
        fontSize: 17,
        marginBottom: 6,
        fontWeight: '600',
        color: '#1e293b',
    },
    produtoPreco: {
        fontSize: 20,
        fontWeight: '700',
        color: '#10b981',
        marginBottom: 4,
    },
    produtoEstoque: {
        fontSize: 13,
        color: '#64748b',
        marginBottom: 6,
        fontWeight: '500',
    },
    produtoDescricao: {
        fontSize: 13,
        color: '#94a3b8',
        fontStyle: 'italic',
        lineHeight: 18,
    },
    botaoAdicionar: {
        backgroundColor: '#10b981',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        shadowColor: '#10b981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
        minWidth: 100,
    },
    botaoDesabilitado: {
        backgroundColor: '#cbd5e1',
        shadowColor: '#cbd5e1',
    },
    botaoTexto: {
        color: '#ffffff',
        fontWeight: '600',
        fontSize: 13,
        textAlign: 'center',
    },
    vazio: {
        alignItems: 'center',
        padding: 60,
        marginHorizontal: 20,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    vazioTexto: {
        textAlign: 'center',
        fontSize: 16,
        color: '#64748b',
        fontWeight: '500',
    },
});