import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    scrollView: {
        flex: 1,
    },
    header: {
        marginBottom: 24,
        paddingTop: 60,
        paddingHorizontal: 20,
    },
    subtitle: {
        fontSize: 16,
        color: '#64748b',
        marginTop: 8,
        fontWeight: '500',
    },
    form: {
        gap: 16,
        marginBottom: 24,
        padding: 24,
        backgroundColor: '#ffffff',
        marginHorizontal: 20,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: '#10b981',
    },
    input: {
        borderWidth: 2,
        borderColor: '#e2e8f0',
        borderRadius: 12,
        padding: 16,
        backgroundColor: '#ffffff',
        fontSize: 16,
        fontWeight: '500',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.02,
        shadowRadius: 4,
        elevation: 1,
    },
    row: {
        flexDirection: 'row',
        gap: 12,
    },
    halfInput: {
        flex: 1,
    },
    categoriasScroll: {
        marginHorizontal: -4,
    },
    categoriasContainer: {
        flexDirection: 'row',
        gap: 8,
        paddingVertical: 4,
    },
    categoriaOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    categoriaOptionIcon: {
        fontSize: 16,
    },
    categoriaOptionText: {
        fontSize: 13,
        fontWeight: '600',
    },
    categoriaOptionSelected: {
        color: '#ffffff',
        fontWeight: '700',
    },
    listaContainer: {
        marginHorizontal: 20,
        marginBottom: 40,
    },
    item: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        padding: 20,
        marginVertical: 8,
        backgroundColor: '#ffffff',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: '#3b82f6',
    },
    infoContainer: {
        flex: 1,
        marginRight: 16,
    },
    detalhes: {
        fontSize: 15,
        color: '#64748b',
        marginTop: 4,
        fontWeight: '500',
    },
    codigoBarras: {
        fontSize: 13,
        color: '#94a3b8',
        marginTop: 4,
        fontWeight: '500',
    },
    descricao: {
        fontSize: 13,
        color: '#94a3b8',
        fontStyle: 'italic',
        marginTop: 6,
        lineHeight: 18,
    },
    acoes: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    controleEstoque: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f1f5f9',
        borderRadius: 12,
        padding: 6,
    },
    botaoEstoque: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#3b82f6',
        borderRadius: 8,
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 2,
    },
    botaoEstoqueTexto: {
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 14,
        lineHeight: 16,
    },
    estoqueNumero: {
        marginHorizontal: 12,
        fontSize: 15,
        fontWeight: '700',
        minWidth: 24,
        textAlign: 'center',
        color: '#1e293b',
    },
    removerBtn: {
        padding: 10,
        backgroundColor: '#fef2f2',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#fecaca',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 1,
    },
    removerText: {
        fontSize: 18,
    },
    vazio: {
        alignItems: 'center',
        padding: 48,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    descricaoVazio: {
        textAlign: 'center',
        marginTop: 12,
        fontSize: 14,
        color: '#94a3b8',
        lineHeight: 20,
    },
});